.Dd May 11, 2018
.Dt TSCRAPE 1
.Os
.Sh NAME
.Nm tscrape
.Nd Twitter scraper
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
reads the Twitter HTML page and scrapes the data into a
TAB-separated format to stdout.
.Sh TAB-SEPARATED FORMAT FIELDS
The items are saved in a TSV-like format.
Control characters are replaced by a single space.
.Pp
The order and content of the fields are:
.Bl -tag -width 17n
.It UNIX timestamp
UNIX timestamp in UTC+0.
.It username
Twitter username (can be a retweet).
.It fullname
Twitter fullname (can be a retweet).
.It tweet text
Tweet text.
.It item id
Item id.
.It item username
Item username.
.It item fullname
Item fullname.
.It item retweetid
Item Retweet ID.
.It item is pinned
Item is pinned or not? 0 or 1.
.El
.Sh EXAMPLES
.Bd -literal -offset left
curl --http1.0 -H 'User-Agent:' -s 'https://twitter.com/namehere' | tscrape
.Ed
.Sh SEE ALSO
.Xr curl 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
